-- H2 (PostgreSQL compatibility mode) mirror of db/migration/V1__init.sql, used by DataSeederTest.

DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS holdings;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS securities;
DROP TABLE IF EXISTS exchanges;

CREATE TABLE exchanges (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(16)  NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    time_zone   VARCHAR(64),
    open_local  TIME,
    close_local TIME,
    open_days   VARCHAR(32)
);

CREATE TABLE securities (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange_id        BIGINT         NOT NULL REFERENCES exchanges (id),
    symbol             VARCHAR(24)    NOT NULL,
    company_name       VARCHAR(160)   NOT NULL,
    currency_native    VARCHAR(8)     NOT NULL,
    snapshot_price_usd NUMERIC(18, 4) NOT NULL,
    UNIQUE (exchange_id, symbol)
);

CREATE TABLE customers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(32)  NOT NULL UNIQUE,
    password_hash    VARCHAR(100) NOT NULL,
    first_name       VARCHAR(64)  NOT NULL,
    last_name        VARCHAR(64)  NOT NULL,
    tax_id           VARCHAR(16)  NOT NULL,
    address_line1    VARCHAR(128) NOT NULL,
    address_line2    VARCHAR(128),
    city             VARCHAR(64)  NOT NULL,
    state            VARCHAR(2)   NOT NULL,
    postal_code      VARCHAR(10)  NOT NULL,
    cash_balance_usd NUMERIC(18, 2) NOT NULL DEFAULT 0
);

CREATE TABLE holdings (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id        BIGINT         NOT NULL REFERENCES customers (id),
    security_id        BIGINT         NOT NULL REFERENCES securities (id),
    quantity           BIGINT         NOT NULL,
    avg_cost_basis_usd NUMERIC(18, 4) NOT NULL,
    UNIQUE (customer_id, security_id)
);

CREATE TABLE transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id        BIGINT       NOT NULL REFERENCES customers (id),
    security_id        BIGINT       NOT NULL REFERENCES securities (id),
    side               VARCHAR(4)   NOT NULL,
    order_type         VARCHAR(6)   NOT NULL,
    status             VARCHAR(8)   NOT NULL,
    quantity           BIGINT       NOT NULL,
    limit_price_usd    NUMERIC(18, 4),
    executed_price_usd NUMERIC(18, 4),
    cash_delta_usd     NUMERIC(18, 2) NOT NULL DEFAULT 0,
    reason             VARCHAR(200),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
