-- Trading app schema (PostgreSQL)

CREATE TABLE exchanges (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(16)  NOT NULL UNIQUE,
    name    VARCHAR(128) NOT NULL,
    enabled BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE securities (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange_id        BIGINT        NOT NULL REFERENCES exchanges (id),
    symbol             VARCHAR(24)   NOT NULL,
    company_name       VARCHAR(160)  NOT NULL,
    currency_native    VARCHAR(8)    NOT NULL,
    snapshot_price_usd NUMERIC(18, 4) NOT NULL CHECK (snapshot_price_usd > 0),
    UNIQUE (exchange_id, symbol)
);

CREATE TABLE customers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(32)  NOT NULL UNIQUE,
    password_hash   VARCHAR(100) NOT NULL,
    first_name      VARCHAR(64)  NOT NULL,
    last_name       VARCHAR(64)  NOT NULL,
    tax_id          VARCHAR(16)  NOT NULL,
    address_line1   VARCHAR(128) NOT NULL,
    address_line2   VARCHAR(128),
    city            VARCHAR(64)  NOT NULL,
    state           VARCHAR(2)   NOT NULL,
    postal_code     VARCHAR(10)  NOT NULL,
    cash_balance_usd NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (cash_balance_usd >= 0)
);

CREATE TABLE holdings (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id        BIGINT         NOT NULL REFERENCES customers (id),
    security_id        BIGINT         NOT NULL REFERENCES securities (id),
    quantity           BIGINT         NOT NULL CHECK (quantity > 0),
    avg_cost_basis_usd NUMERIC(18, 4) NOT NULL CHECK (avg_cost_basis_usd > 0),
    UNIQUE (customer_id, security_id)
);

CREATE TABLE transactions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       BIGINT       NOT NULL REFERENCES customers (id),
    security_id       BIGINT       NOT NULL REFERENCES securities (id),
    side              VARCHAR(4)   NOT NULL CHECK (side IN ('BUY', 'SELL')),
    order_type        VARCHAR(6)   NOT NULL CHECK (order_type IN ('MARKET', 'LIMIT')),
    status            VARCHAR(8)   NOT NULL CHECK (status IN ('FILLED', 'REJECTED')),
    quantity          BIGINT       NOT NULL CHECK (quantity > 0),
    limit_price_usd   NUMERIC(18, 4),
    executed_price_usd NUMERIC(18, 4),
    cash_delta_usd    NUMERIC(18, 2) NOT NULL DEFAULT 0,
    reason            VARCHAR(200),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_securities_exchange ON securities (exchange_id);
CREATE INDEX idx_holdings_customer ON holdings (customer_id);
CREATE INDEX idx_transactions_customer_created ON transactions (customer_id, created_at DESC);
